### ISSUE TITLE
is there an injection feature in the method class?

### ISSUE THREAD

**Issue by viandwi24** [luvies/deno_di#2]
is there an injection feature in the method class? like :

thanks.
```
@Service()
class Money {
}


@Service()
class Wallet {

      @Inject
      public add(money: Money) {
      }
}
```

**Comment by luvies** [comment]
That currently is not a feature, no. What would be the use-case? It feels like there would be a lot of possible ways to implement this (which would be odd or complex).

I would rather keep this module simple really, did you have specific way this would work? (i.e. would it get an instance from the container on every call?)

**Comment by luvies** [comment]
Since this issue is stale, and I don’t see the use case of something like this, I’m going to close this.
